
/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/8.0.2/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:5.9.1")

    // https://mvnrepository.com/artifact/org.json/json

    // https://mvnrepository.com/artifact/org.mariadb.jdbc/mariadb-java-client
    implementation("org.mariadb.jdbc:mariadb-java-client:3.3.2")
    // https://mvnrepository.com/artifact/jakarta.websocket/jakarta.websocket-api
    implementation("jakarta.websocket:jakarta.websocket-api:2.2.0-M1")

    implementation("com.google.code.gson:gson:2.10.1")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:31.1-jre")


    implementation("io.github.cdimascio:dotenv-java:3.0.0")

}

application {
    // Define the main class for the application.
    mainClass.set("javahttp.App")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

//build jar task
tasks.named<Jar>("jar") {
    manifest {
        attributes["Main-Class"] = "javahttp.Server"
    }
    from(sourceSets.main.get().output)
}